name: Run bulid test and lint files
"on": push
jobs:
  unit_test-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
              cd "/# Final Project/client"
              npm ci
              npm run build
              npm run lint